# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-28 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20160424_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('leave_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_message_to', to=settings.AUTH_USER_MODEL)),
                ('who_leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_leave_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_message',
            },
        ),
    ]
